In [5]:
import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

In [2]:

def initialize_membership_matrix(num_samples, num_clusters):
    # Initialize the membership matrix randomly
    membership_mat = np.random.rand(num_clusters, num_samples)
    # Normalize the membership matrix
    membership_mat /= np.sum(membership_mat, axis=0)
    return membership_mat

def calculate_centroids(data, membership_mat, num_clusters, fuzziness):
    # Calculate centroids
    centroids = np.zeros((num_clusters, data.shape[1]))
    for k in range(num_clusters):
        # Compute the denominator
        denominator = np.sum((membership_mat[k, :] ** fuzziness))
        for j in range(data.shape[1]):
            # Compute the numerator
            numerator = np.sum((membership_mat[k, :] ** fuzziness) * data[:, j])
            centroids[k, j] = numerator / denominator
    return centroids

def update_membership_matrix(data, centroids, num_clusters, fuzziness):
    # Update the membership matrix
    num_samples = data.shape[0]
    membership_mat = np.zeros((num_clusters, num_samples))
    for i in range(num_samples):
        for k in range(num_clusters):
            # Compute the distance between the sample and the centroid
            distances = np.linalg.norm(data[i] - centroids[k])
            # Avoid division by zero
            if distances == 0:
                membership_mat[k, i] = 1
            else:
                membership_mat[k, i] = 1 / np.sum((distances / np.linalg.norm(data[i] - centroids)) ** (2 / (fuzziness - 1)))
    # Normalize the membership matrix
    membership_mat /= np.sum(membership_mat, axis=0)
    return membership_mat

def fuzzy_c_means_clustering(data, num_clusters, fuzziness=2, max_iter=100, error=1e-6, random_state=None):
    """
    Perform Fuzzy C-means clustering on the given data.

    Parameters:
    data : array-like, shape (n_samples, n_features)
        Input data.
    num_clusters : int
        Number of clusters.
    fuzziness : float, optional (default=2)
        Exponent for the fuzzy partition matrix, where higher values indicate fuzzier clusters.
    max_iter : int, optional (default=100)
        Maximum number of iterations.
    error : float, optional (default=1e-6)
        Error tolerance to declare convergence.
    random_state : int or RandomState, optional (default=None)
        Seed for random number generation.

    Returns:
    centroids : array, shape (num_clusters, n_features)
        Centroids of the clusters.
    membership_mat : array, shape (num_clusters, n_samples)
        Final fuzzy partition matrix.
    """
    np.random.seed(random_state)
    num_samples = data.shape[0]
    # Initialize membership matrix
    membership_mat = initialize_membership_matrix(num_samples, num_clusters)
    # Initialize centroids
    centroids = calculate_centroids(data, membership_mat, num_clusters, fuzziness)
    
    for _ in range(max_iter):
        # Keep the old centroids to check convergence
        old_centroids = centroids.copy()
        # Update membership matrix
        membership_mat = update_membership_matrix(data, centroids, num_clusters, fuzziness)
        # Update centroids
        centroids = calculate_centroids(data, membership_mat, num_clusters, fuzziness)
        # Check convergence
        if np.linalg.norm(centroids - old_centroids) < error:
            break
    
    return centroids, membership_mat


In [14]:
# Example usage:
# Generate random data
np.random.seed(0)
data = np.random.rand(100, 2)

# Perform fuzzy C-means clustering
num_clusters = 3
centroids, membership_mat = fuzzy_c_means_clustering(data, num_clusters)

print("Centroids:")
print(centroids)

print("matrix membership")
print(membership_mat.T)


Centroids:
[[0.22741441 0.71995374]
 [0.76312626 0.6007064 ]
 [0.51807828 0.18663905]]
matrix membership
[[0.32064527 0.56116722 0.11818751]
 [0.12172444 0.72418988 0.15408568]
 [0.63481891 0.23813375 0.12704733]
 [0.652417   0.25212861 0.09545438]
 [0.0888268  0.66585391 0.24531928]
 [0.01606275 0.95424535 0.0296919 ]
 [0.41823045 0.46106418 0.12070536]
 [0.27793712 0.15900512 0.56305776]
 [0.85073091 0.07812656 0.07114253]
 [0.16425208 0.73564474 0.10010318]
 [0.11600722 0.77128348 0.1127093 ]
 [0.61041254 0.28933079 0.10025667]
 [0.91405507 0.04011397 0.04583096]
 [0.83676745 0.09586865 0.0673639 ]
 [0.15632646 0.30295104 0.5407225 ]
 [0.97457808 0.01512779 0.01029413]
 [0.43605279 0.34453015 0.21941706]
 [0.81865756 0.07974018 0.10160226]
 [0.1150629  0.79087096 0.09406613]
 [0.06521947 0.85607206 0.07870847]
 [0.3811237  0.19587536 0.42300094]
 [0.05943198 0.13160122 0.80896679]
 [0.06430358 0.88666845 0.04902797]
 [0.19123786 0.12659921 0.68216293]
 [0.29550052 0.15506872 0.54943